server:
  port: 8080
spring:
  application:
    name: spring-boot-server
  datasource:
    url: jdbc:mysql://localhost:3306/adventureworks
    username: devuser
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
  security:
    user:
      name: service
#      password: 3b99fef5-8b7d-4984-a3d6-124c26914ed7
      password: 123
logging:
  file:
    name: /Coding/Logging/${spring.application.name}/log
management:
  endpoints:
    enabled-by-default: true
    web.exposure.include: health, info, metric
  endpoint:
    info:
      enabled: true
    health:
      show-details: always
